# Generated by Django 4.2.8 on 2023-12-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_alter_task_executor_delete_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='title',
        ),
    ]
